version: "3.9"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - ./datavolume:/var/lib/mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Root_password!
      MYSQL_DATABASE: backend_db
