version: "3.9"
services:
  app:
    build: .
    platform: linux/x86_64
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      - ENVIRONMENT=staging
      - PORT=3001
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Root_password!
      - MYSQL_DATABASE=backend_db
    
  db:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - ./datavolume:/var/lib/mysql
    ports:
      - 3316:3306
    environment:
      MYSQL_ROOT_PASSWORD: Root_password!
      MYSQL_DATABASE: backend_db
